/* 
  Sketch generated by the Arduino IoT Cloud Thing "Cloud Blink"
  
  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  bool servoSwitch;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/
/* 
  Sketch for controlling a servo motor through Arduino IoT Cloud.

  Variables generated by Arduino IoT Cloud Thing:

  - bool servoSwitch: Toggles the servo between 0 and 45 degrees.
*/

#include "thingProperties.h"
#include <Servo.h>

// Create a Servo object
Servo myServo;
const int servoPin = 9; // Servo connected to pin 9

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  delay(1500); // Wait for the Serial Monitor to initialize

  // Initialize IoT Cloud properties
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  // Debug information
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();

  // Initialize the servo motor
  myServo.attach(servoPin);
  myServo.write(0); // Set servo to initial position (0 degrees)
}

void loop() {
  // Update the IoT Cloud connection
  ArduinoCloud.update();
}

/*
  Since servoSwitch is READ_WRITE, onServoSwitchChange() is called
  every time the variable is updated from the IoT Cloud.
*/
void onServoSwitchChange() {
  if (servoSwitch) {
    myServo.write(40); // Move servo to 45 degrees
    Serial.println("Servo moved to 40 degrees");
  } else {
    myServo.write(0); // Move servo back to 0 degrees
    Serial.println("Servo moved to 0 degrees");
  }
}



/*
  Since Led is READ_WRITE variable, onLedChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLedChange()  {
  // Add your code here to act upon Led change
}
/*
  Since Mode is READ_WRITE variable, onModeChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onModeChange()  {
  // Add your code here to act upon Mode change
}


